name: Minify Kuy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2
        with:
          repository: abdiemes.github.io/mona-abdi

      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1

      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Minify code'
          branch: ${{ github.ref }}