name: Minify Kuy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1
        with:
          directory: 'mona-abdi/index.html'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Minify Action : Commit Pipeline'
          branch: ${{ github.ref }}