name: Minify Kuy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest      # Docker-based github actions have to run on a linux environment
    steps:
      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:latest   # To use a specific release, use a docker tag like 1.0.2 instead of latest
        with:
          directory: '~/mona-abdi' # Optional
          add_suffix: false      # Optional

      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'HTML/CSS/JS Minifier : Commit Pipeline'
          branch: ${{ github.ref }}